### ISSUE TITLE
./geekbookapp.py -d rna-structure-mRNA

### ISSUE THREAD

**Issue by mmagnus** [mmagnus/geekbook#54]
```
[mm] geekbook git:(master) ✗ ./geekbookapp.py -d rna-structure-mRNA
2017-04-12 12:57:26,004 - geekbookapp.py - G33kB00k is Running... [ok]
2017-04-12 12:57:26,004 - geekbookapp.py - root path: /Users/magnus/Dropbox
2017-04-12 12:57:26,004 - geekbookapp.py - html path: <file:///Users/magnus/Dropbox/geekbook/engine/data/html/index.html>
2017-04-12 12:57:26,004 - geekbookapp.py - imgs path: /Users/magnus/Dropbox/geekbook/notes/
2017-04-12 12:57:26,005 - geekbookapp.py - Ready to go! Please edit me: notes/
2017-04-12 12:57:26,017 - geekbookapp.py - You have 511 notes! Congrats, keep noting!
2017-04-12 12:57:26,284 - md_update.py - file removed rna-structure-mRNA
Traceback (most recent call last):
  File "./geekbookapp.py", line 262, in <module>
    a.start()
  File "./geekbookapp.py", line 183, in start
    changed = m.compile() # if changed MD
  File "/Users/magnus/Dropbox/geekbook/engine/md_update.py", line 40, in compile
    self.md, is_get_ss = get_ss(self.md)
AttributeError: 'Md_update' object has no attribute 'md'
```

**Comment by mmagnus** [comment]
```./geekbookapp.py -d test
/Users/magnus/Dropbox/geekbook
2017-07-10 13:40:27,565 - geekbookapp.py - Start off flask!
searcher::making the db
/Users/magnus/Dropbox/geekbook
/Users/magnus/Dropbox/geekbook/themes/default/notes/head.html
/Users/magnus/Dropbox/geekbook
Traceback (most recent call last):
  File "/Users/magnus/Dropbox/geekbook/engine/webserverflask.py", line 102, in <module>
    app.run(debug=True)#
  File "/home/magnus/work/opt/miniconda2/lib/python2.7/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/magnus/work/opt/miniconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 691, in run_simple
    s.bind((hostname, port))
  File "/home/magnus/work/opt/miniconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
```
