### ISSUE TITLE
include_md_files - crashes if there is no file

### ISSUE THREAD

**Issue by mmagnus** [mmagnus/geekbook#72]
```
Traceback (most recent call last):
  File "./geekbookapp.py", line 296, in <module>
    app.start()
  File "./geekbookapp.py", line 179, in start
    p.compile()
  File "/Users/magnus/Dropbox/geekbook/engine/page.py", line 59, in compile
    self.pre_process()
  File "/Users/magnus/Dropbox/geekbook/engine/page.py", line 69, in pre_process
    self.md = include_md_files(self.md)
  File "/Users/magnus/Dropbox/geekbook/engine/preprocessing.py", line 183, in include_md_files
    with codecs.open(ffullpath, "r", "utf-8") as f:
  File "/home/magnus/work/opt/miniconda2/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/Users/magnus/Dropbox/geekbook/notes//rp06evo.md'
````

**Comment by mmagnus** [comment]
![screen shot 2017-11-03 at 8 56 53 pm](https://user-images.githubusercontent.com/118740/32393383-8837ea86-c0d9-11e7-9f95-486efdc4b72f.png)
